### ISSUE TITLE
Republish last version due to spurious permissions in tarball

### ISSUE THREAD

**Issue by ignatenkobrain** [Emerentius/ord_subset#5]
I see that last tarball on crates.io has all files with executable bit which creates some problems when packaging for Fedora.

I would appreciate if you would release new version where tarball would not have those files with exec perms. Thanks in advance!

**Comment by ignatenkobrain** [comment]
https://crates.io/api/v1/crates/ord_subset/3.1.0/download#/ord_subset-3.1.0.crate

**Comment by Emerentius** [comment]
I see, it's a side-effect of me using an NTFS shared partition for my code. Everything is treated as executable. I've published v3.1.1 without executable bits set.

Whar problems are these permissions causing exactly? I would think they are under the packagers control anyway.
